services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      APP_ENV: demo
      DEMO_MODE: "true"
      DATABASE_URL: sqlite:////app/data/triageai_demo.sqlite
      MODEL_PATH: model_artifacts/esi_345_lightgbm_v2_threshold.txt
      THRESHOLDS_PATH: model_artifacts/thresholds.json
      FEATURE_SCHEMA_PATH: model_artifacts/feature_schema.json
      MODEL_METADATA_PATH: model_artifacts/model_metadata.json
      REPORT_OUTPUT_DIR: /app/reports/generated
    ports:
      - "8001:8001"
    volumes:
      - triageai_sqlite_data:/app/data
      - triageai_reports:/app/reports/generated

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      APP_ENV: demo
      DEMO_MODE: "true"
      TRIAGEAI_BACKEND_URL: http://backend:8001
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  triageai_sqlite_data:
  triageai_reports:
