[client]
showSidebarNavigation = false
toolbarMode = "viewer"

[theme]
primaryColor = "#0284c7"
backgroundColor = "#eaf5fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
